// Generated by LiveScript 1.2.0
(function(){
  var color;
  color = function(code){
    return function(){
      process.stdout.write("\x1b[" + code + "m");
      console.log.apply(this, arguments);
      return process.stdout.write("\x1b[0m");
    };
  };
  module.exports = {
    color: color,
    red: color('0;31'),
    green: color('0;32'),
    brown: color('0;33'),
    blue: color('0;34'),
    purple: color('0;35'),
    alt: function(){
      var colors, ctr;
      colors = ['red', 'green', 'brown', 'blue', 'purple'];
      ctr = 0;
      return function(){
        this[colors[ctr++]].apply(this, arguments);
        return ctr %= colors.length;
      };
    }()
  };
}).call(this);
